# Generated by Django 3.2.7 on 2021-10-02 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemaRM', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='personalAdmin',
        ),
    ]
